  
name: build

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Try to restore build cache
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.opam
            ~/bin
          key: ${{ runner.os }}-${{ hashFiles('opam') }}
          restore-keys : |
            ${{ runner.os }}-${{ hashFiles('opam') }}
            ${{ runner.os }}-

      - name: Install OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.09.1+flambda

      - run: opam repo add coq-released https://coq.inria.fr/opam/released
      - run: opam update
      - run: opam pin add coq-library-undecidability.dev+8.16 "https://github.com/uds-psl/coq-library-undecidability.git#coq-8.16"
      - run: opam exec -- make all -j2 TIMED=1
